INSERT INTO food_items (name, serving_size, calories) VALUES ('Apple', '1 medium', 95);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Banana', '1 medium', 105);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Orange', '1 medium', 62);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Pear', '1 medium', 101);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Peach', '1 medium', 59);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Grapes', '1 cup', 104);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Strawberries', '1 cup', 49);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Blueberries', '1 cup', 84);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Raspberries', '1 cup', 64);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Blackberries', '1 cup', 62);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Watermelon', '1 cup', 46);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Pineapple', '1 cup', 82);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Mango', '1 cup', 99);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Kiwi', '1 medium', 42);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Grapefruit', '1/2 fruit', 52);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Plum', '1 medium', 30);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cherries', '1 cup', 77);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cantaloupe', '1 cup', 53);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Honeydew', '1 cup', 61);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Avocado', '1/2 fruit', 120);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Tomato', '1 medium', 22);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cucumber', '1/2 cucumber', 8);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Carrot', '1 medium', 25);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Baby Carrots', '10 pieces', 35);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Broccoli', '1 cup cooked', 55);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cauliflower', '1 cup cooked', 29);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Spinach', '1 cup raw', 7);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Kale', '1 cup raw', 33);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Romaine Lettuce', '2 cups', 16);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Mixed Greens', '2 cups', 20);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Bell Pepper', '1 medium', 24);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Onion', '1 medium', 44);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Zucchini', '1 cup cooked', 27);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Green Beans', '1 cup cooked', 44);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Peas', '1 cup', 118);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Corn', '1 ear', 77);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Sweet Potato', '1 medium baked', 103);
INSERT INTO food_items (name, serving_size, calories) VALUES ('White Potato', '1 medium baked', 161);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Mashed Potatoes', '1 cup', 214);
INSERT INTO food_items (name, serving_size, calories) VALUES ('French Fries', 'small order', 230);
INSERT INTO food_items (name, serving_size, calories) VALUES ('White Rice', '1 cup cooked', 205);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Brown Rice', '1 cup cooked', 216);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Quinoa', '1 cup cooked', 222);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Oatmeal', '1 cup cooked', 158);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Granola', '1/2 cup', 200);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Corn Flakes', '1 cup', 100);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cheerios', '1 cup', 104);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Whole Wheat Bread', '1 slice', 80);
INSERT INTO food_items (name, serving_size, calories) VALUES ('White Bread', '1 slice', 75);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Bagel', '1 medium', 250);
INSERT INTO food_items (name, serving_size, calories) VALUES ('English Muffin', '1 whole', 120);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Flour Tortilla', '8 inch', 140);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Corn Tortilla', '6 inch', 50);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Croissant', '1 medium', 230);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Pancakes', '2 small', 175);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Waffle', '1 round', 220);
INSERT INTO food_items (name, serving_size, calories) VALUES ('French Toast', '1 slice', 149);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Plain Donut', '1 medium', 195);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Blueberry Muffin', '1 medium', 385);
INSERT INTO food_items (name, serving_size, calories) VALUES ('White Pasta', '1 cup cooked', 200);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Whole Wheat Pasta', '1 cup cooked', 180);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Mac and Cheese', '1 cup', 310);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Spaghetti with Marinara', '1 cup', 190);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Lasagna', '1 piece', 336);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cheese Pizza', '1 slice', 285);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Pepperoni Pizza', '1 slice', 313);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Hamburger', '1 sandwich', 250);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cheeseburger', '1 sandwich', 300);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Hot Dog', '1 with bun', 150);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Grilled Chicken Breast', '3 oz', 140);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Chicken Thigh', '3 oz cooked', 180);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Rotisserie Chicken', '3 oz', 160);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Turkey Breast', '3 oz', 125);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Ground Beef (85% lean)', '3 oz cooked', 215);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Sirloin Steak', '3 oz', 180);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Pork Chop', '3 oz', 190);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Bacon', '2 slices', 80);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Ham', '3 oz', 120);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Sausage Link', '1 link', 95);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Turkey Sausage', '1 link', 70);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Salmon', '3 oz baked', 175);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Tuna (canned in water)', '3 oz', 110);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Shrimp', '3 oz boiled', 84);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cod', '3 oz baked', 90);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Tilapia', '3 oz baked', 110);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Egg', '1 large', 72);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Egg White', 'from 1 egg', 17);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Scrambled Eggs', '2 eggs', 180);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cheese Omelet', '2 eggs', 250);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Greek Yogurt (plain)', '1 cup', 100);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Greek Yogurt (fruit)', '1 cup', 150);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Regular Yogurt', '6 oz', 140);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cottage Cheese', '1/2 cup', 110);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cheddar Cheese', '1 oz', 115);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Mozzarella Cheese', '1 oz', 85);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Swiss Cheese', '1 oz', 110);
INSERT INTO food_items (name, serving_size, calories) VALUES ('String Cheese', '1 stick', 80);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Butter', '1 tbsp', 102);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Margarine', '1 tbsp', 100);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Peanut Butter', '2 tbsp', 190);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Almond Butter', '2 tbsp', 196);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Jam or Jelly', '1 tbsp', 56);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Honey', '1 tbsp', 64);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Mayonnaise', '1 tbsp', 94);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Ketchup', '1 tbsp', 20);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Mustard', '1 tbsp', 10);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Ranch Dressing', '2 tbsp', 145);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Italian Dressing', '2 tbsp', 80);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Caesar Dressing', '2 tbsp', 160);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Hummus', '2 tbsp', 60);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Guacamole', '2 tbsp', 50);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Sour Cream', '2 tbsp', 60);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Potato Chips', '1 oz', 152);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Tortilla Chips', '1 oz', 140);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Popcorn (air-popped)', '3 cups', 90);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Pretzels', '1 oz', 108);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Salted Peanuts', '1 oz', 166);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Almonds', '1 oz', 164);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cashews', '1 oz', 157);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Walnuts', '1 oz', 185);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Pistachios', '1 oz', 159);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Trail Mix', '1/4 cup', 175);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Granola Bar', '1 bar', 100);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Protein Bar', '1 bar', 210);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Banana Bread', '1 slice', 196);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Brownie', '1 piece', 130);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Chocolate Chip Cookie', '1 medium', 160);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Oatmeal Cookie', '1 medium', 100);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cupcake', '1 small', 200);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Chocolate Cake', '1 slice', 350);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Vanilla Ice Cream', '1/2 cup', 137);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Chocolate Ice Cream', '1/2 cup', 145);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Frozen Yogurt', '1/2 cup', 115);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Sherbet', '1/2 cup', 105);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Apple Pie', '1 slice', 296);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Pumpkin Pie', '1 slice', 323);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cheesecake', '1 slice', 401);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Dark Chocolate', '1 oz', 170);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Milk Chocolate', '1.5 oz bar', 210);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Gummy Candy', '10 pieces', 140);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Hard Candy', '3 pieces', 70);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Apple Juice', '8 fl oz', 114);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Orange Juice', '8 fl oz', 112);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Grape Juice', '8 fl oz', 152);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Soda (regular)', '12 fl oz', 150);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Soda (diet)', '12 fl oz', 2);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Lemonade', '8 fl oz', 99);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Sports Drink', '8 fl oz', 50);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Whole Milk', '1 cup', 150);
INSERT INTO food_items (name, serving_size, calories) VALUES ('2% Milk', '1 cup', 120);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Skim Milk', '1 cup', 83);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Unsweetened Almond Milk', '1 cup', 30);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Soy Milk', '1 cup', 100);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Latte (whole milk)', '12 fl oz', 180);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Black Coffee', '8 fl oz', 2);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Tea (unsweetened)', '8 fl oz', 2);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Sweet Tea', '12 fl oz', 140);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Energy Drink', '8 fl oz', 110);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Chili with Beans', '1 cup', 260);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Beef Stew', '1 cup', 250);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Chicken Noodle Soup', '1 cup', 75);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Tomato Soup', '1 cup', 90);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Vegetable Soup', '1 cup', 80);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Lentil Soup', '1 cup', 180);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Black Bean Soup', '1 cup', 245);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Baked Beans', '1/2 cup', 140);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Refried Beans', '1/2 cup', 120);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Chickpeas', '1/2 cup cooked', 135);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Black Beans', '1/2 cup cooked', 114);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Kidney Beans', '1/2 cup cooked', 110);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Firm Tofu', '3 oz', 70);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Tempeh', '3 oz', 160);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Veggie Burger', '1 patty', 120);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Falafel', '3 small pieces', 160);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Edamame', '1/2 cup', 95);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Mixed Nuts', '1 oz', 170);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Sunflower Seeds', '1 oz', 165);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Pumpkin Seeds', '1 oz', 151);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Rice Cake', '1 cake', 35);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Saltine Crackers', '5 crackers', 60);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Graham Crackers', '2 squares', 90);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Pita Bread', '6 inch', 170);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Garlic Bread', '1 slice', 150);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Coleslaw', '1 cup', 150);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Potato Salad', '1 cup', 350);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Chicken Salad (with mayo)', '1 cup', 400);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Tuna Salad (with mayo)', '1/2 cup', 190);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Garden Salad (with dressing)', '2 cups', 180);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Caesar Salad', '2 cups', 330);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Greek Salad', '2 cups', 400);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Stir Fry Vegetables', '1 cup', 120);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Chicken Stir Fry', '1 cup', 250);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Fried Rice', '1 cup', 330);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Chicken Curry', '1 cup', 300);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Beef Taco', '1 taco', 170);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Chicken Taco', '1 taco', 150);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Bean Burrito', '1 medium', 290);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Cheese Quesadilla', '1 wedge', 220);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Sushi Roll', '1 piece', 35);
INSERT INTO food_items (name, serving_size, calories) VALUES ('California Roll', '6 pieces', 250);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Chicken Nuggets', '6 pieces', 280);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Fish Sticks', '4 pieces', 190);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Fried Chicken Drumstick', '1 piece', 160);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Turkey Sandwich', '1 sandwich', 280);
INSERT INTO food_items (name, serving_size, calories) VALUES ('Grilled Cheese', '1 sandwich', 320);
